[package]
name = "tclifford"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "*"
itertools = "*"
ndarray = ">=0.16.0"
static_assertions = "1.1.0"
opimps = "*"

[dev-dependencies]
rand = "*"
num-integer = "*"
